apiVersion: batch/v1
kind: CronJob
metadata:
  name: sealedsecrets-backup
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: 0 3 * * * # backup will run once per day
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sealedsecrets-backup-reader
          containers:
          - name: ose-cli-container
            image: registry.redhat.io/openshift4/ose-cli
            command: ["/bin/sh"]
            args: ["-c", "/scripts/backup.sh"]
            envFrom:
              - secretRef:
                  name: sealedsecrets-backup-s3
            volumeMounts:
            - name: backup-script
              mountPath: /scripts
          restartPolicy: Never
          volumes:
          - name: backup-script
            configMap:
              name: sealedsecrets-backup-script
              defaultMode: 0755
      backoffLimit: 4