kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: sealedsecrets-backup-reader
subjects:
- kind: ServiceAccount
  name: sealedsecrets-backup-reader
roleRef:
 kind: Role
 name: sealedsecrets-backup-reader
 apiGroup: rbac.authorization.k8s.io